# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김정우
title: 웹 백엔드 개발자
email: wjddn312@naver.com
website: https://velog.io/@kjw1995/posts

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  kjw1995
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jfif
about_content: | # this will include new lines to allow paragraphs
  <mark>Java, Spring / 클라우드 서버 기반의 1년차 서버 백엔드 개발자</mark>입니다. <br /> 
  P2P 금융 핀테크 사의 기존 레거시 소스들의 리팩토링, 유지보수, 신규개발. 동시간대 회원 상품 투자의 모니터링 및 해당 프로세스 개발을 담당하였습니다. <br /> 
  동료 개발자들 간의 원활한 협력을 위하여, 간결한 코드 작성 및 테스트 코드로 높은 확장성을 지향하고있습니다. <br /> 
  

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (주)헬로핀테크
        link: hellofunding.co.kr
        # link_text: boringcompany.com
        sub_title: 웹 개발자
        caption: 2023.02 ~
        quote: >
          누적투자금액 2조원, P2P 금융 핀테크
        description: | # this will include new lines to allow paragraphs
            - 사내 레거시 코드 리팩토링 진행(2023.02 ~ 2023.11)
              - 기존 MyBatis(ORM) 의 코드 JPA 리팩토링 진행
                - 기존 회원 인증방식(KYC) 소스 코드 리팩토링(2023.02 ~ 2023.03)
                - 로그인 서비스 리팩토링(2023.03 ~ 2023.04)
                - 세금계산서 및 현금영수증 발행 서비스 리팩토링(2023.10.24 ~ 2023.11.17)
            - 사내 업무 개발 및 유지보수 진행(2023.02~)
              - 국세청 세금 계산서 발행 API 연동 개발(2023.08.17 ~ 2023.08.29)
              - Spring Boot 버전 업 및 버전 업에 따른 Spring Security 설정 수정(2023.05.29 ~ 2023.06.29)
              - 사내 지급 통계 데이터 프로시저 등록 및 백오피스 통계 페이지 개발(2023.12.01 ~ 2023.12.11)
            - 신규 프로젝트 및 개발 진행
              - 개발자 API 레퍼런스 페이지 애플리케이션 설정 및 개발(2023.04 ~ 2023.08)
              - OPENAPI 서버 구축(2023.04.01 ~ 2023.04.25)
                - Spring Security(JWT) 인증 방식 도입을 통한 인증,인가 설정(2023.04.26 ~ 2023.05.09)
                - 기존 내부 서버 상품 및 투자 서비스 연동 개발(2023.07.25 ~ 2023.08.09)
              - 정산자동화를 위한 다수의 PG사 정산대사API 연동개발 및 배치서비스 개발(2023.12.15 ~ 2024.02.05)
              - P2P 대출자 PG 결제 서비스 개발
                - 외부 API 와의 연동 및 결제 후 승인 처리 서비스 개발(2024.11.19 ~ 2024.11.26)
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: BackEnd
        quote: 현재 업무에서 사용하고있거나, 경험했던 기술들 입니다.
        description: | # this will include new lines to allow paragraphs
          - Java, Spring FrameWork, Spring Boot(Thymeleaf)
          - Spring Security, JWT, Spring Batch, Spring Quartz, Spring Mvc
          - MyBatis, JPA, QueryDsl
          - Redis
          - Gradle, Groovy, Intellij
      - layout: left
        title: FrontEnd
        description: |
          - JavaScript(JQuery)
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
          - MySQL
          - Nginx, Apache
          - Linux Centos
          - Docker, Kubernetes, ElasticsSearch, Grafana, Prometheus
          - GitLab. Jenkins, ArgoCD. Slack
  - title: OpenSource
    layout: list
    content:
      - layout: left
        title: 개인블로그
        quote: 개인 기술 블로그
        link: https://velog.io/@kjw1995/posts
        description: |
          - 업무 중 발생했던 문제, 회사에서 사용하는 기술, 여러 동료 개발자들과의 협업 시 생기는 문제 해결 방안 등 스스로 정리하고 공부하기 위함

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
